import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import Header from 'components/Header';
import { AuthProvider } from 'hooks/useAuth';
import { LANGUAGES, LanguageType } from 'i18n/settings';
import { dir } from 'i18next';
import '../../styles/_reset.css';
import '../../styles/globals.scss';
import theme from '../../theme/theme';
import SignIn from './(auth)/signin/page';
import SignUp from './(auth)/signup/page';

export async function generateStaticParams() {
  return LANGUAGES.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutPropsType = Readonly<{
  children: React.ReactNode;
  params: { lng: LanguageType };
}>;

export default function RootLayout({ children, params: { lng } }: RootLayoutPropsType) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <AuthProvider>
            <ThemeProvider theme={theme}>
              <Header lng={lng} />
              {children}
              <SignUp />
              {/* delete - temporary solution */}
              <SignIn />
              {/* delete - temporary solution */}
            </ThemeProvider>
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
