import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { dir } from 'i18next';

import { LanguageType, languages } from '../i18n/settings';
import './globals.css';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutPropsType = Readonly<{
  children: React.ReactNode;
  params: { lng: LanguageType };
}>;

export default function RootLayout({ children, params: { lng } }: RootLayoutPropsType) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
